### ISSUE TITLE
Wrong argument in event

### ISSUE THREAD

**Issue by MerlinEgalite** [convex-eth/platform#10]
## Issue

The `morpho` address is logged in the transfer ownership event instead of `morpho.owner()`:
https://github.com/convex-eth/platform/blob/c8c14b0d31999eeeede58ebff1e6d696139ec4cf/contracts/contracts/wrappers/ConvexStakingWrapperMorpho.sol#L52

## Recommendation

Consider logging `morpho.owner()` instead.

**Comment by C2tP-C2tP** [comment]
fix in [b95d5b5](https://github.com/convex-eth/platform/commit/b95d5b5559f4fda2644c8d9c38e0f3700fb4b587)
