### ISSUE TITLE
`setMorphoId` frontrunning

### ISSUE THREAD

**Issue by MerlinEgalite** [convex-eth/platform#5]
The following function has no restriction on who can call it and thus someone could highjack the contract: https://github.com/convex-eth/platform/blob/c8c14b0d31999eeeede58ebff1e6d696139ec4cf/contracts/contracts/wrappers/ConvexStakingWrapperMorpho.sol#L71

**Comment by C2tP-C2tP** [comment]
It gets that collateral check from morpho itself. You can't give it a bogus id and get a fake market returned.
Also the wrapper needs to exist/be known before adding it to morpho as a new market.
