### ISSUE TITLE
Non compliant interface to ERC20Wrapper

### ISSUE THREAD

**Issue by MerlinEgalite** [convex-eth/platform#8]
## Issue

The current interface is the following:
https://github.com/convex-eth/platform/blob/c8c14b0d31999eeeede58ebff1e6d696139ec4cf/contracts/contracts/wrappers/ConvexStakingWrapperMorpho.sol#L118-L120

while the correct interface is:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/e83142944f1d53cf31149b09254f91ef622537bd/contracts/token/ERC20/extensions/ERC20Wrapper.sol#L57

## Recommendation

Consider complying to the correct interface, else, the call via our bundler contract won't work.

**Comment by C2tP-C2tP** [comment]
fixed in 5eab742
