### ISSUE TITLE
Attackers can mint any amount of collateral on Morpho

### ISSUE THREAD

**Issue by MerlinEgalite** [convex-eth/platform#9]
## Issue

On transfer from `user != (morpho || address(this))` nothing is done. Hence, use can directly `supplyCollateral` on Morpho Blue and create position with an arbitrary number of collateral tokens.
https://github.com/convex-eth/platform/blob/c8c14b0d31999eeeede58ebff1e6d696139ec4cf/contracts/contracts/wrappers/ConvexStakingWrapperMorpho.sol#L173

## Recommendation

Revert on transfer.

**Comment by C2tP-C2tP** [comment]
Should be fixed in f5f81a9

add if FROM is not wrapper, then TO must also not be morpho
